# Generated by Django 2.1.7 on 2019-02-21 17:51

from django.db import migrations

def add_data(apps, schema_editor):
    Company = apps.get_model('jobs', 'Company')
    Nike = Company(name="Nike", city="New York", state = "NY")
    Nike.save()




class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
