# Generated by Django 2.1.7 on 2019-02-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='embed_content_link',
        ),
    ]
