# Generated by Django 2.1.7 on 2019-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190221_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
    ]
