# Generated by Django 2.1.7 on 2019-02-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_company_embed_content_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='embed_lik',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
