# Generated by Django 2.1.7 on 2019-02-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_company_embed_lik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='embed_lik',
            new_name='embed_link',
        ),
    ]
