# Generated by Django 2.1.7 on 2019-02-21 19:05

from django.db import migrations

def add_data(apps, schema_editor):
    Company = apps.get_model('jobs', 'Company')
    Nike = Company(name="Nike", city="New York", state = "NY")
    Nike.save()
    Wall_Street_Journal = Company(name="The Wall Street Journal", city="New York", state="NY")
    Wall_Street_Journal.save()



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190221_1044'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
