# Generated by Django 2.1.7 on 2019-02-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
