# Generated by Django 2.1.7 on 2019-02-24 23:27

from django.db import migrations


def create_companies(apps, schema_editor):

    Company = apps.get_model('jobs', 'Company')
    Outdoor_Voices = Company(name="Outdoor_Voices", city="Austin", state="TX",
        about= """ We believe in Doing Things — moving your body and having fun
        with friends. From dog jogs to dodgeball, we make clothes for sweating
        without the added pressure. Our team is made up of casual Recreationalists
        who approach activity with ease, humor, and delight. Since launching
        in 2014, Outdoor Voices has been featured in The New York Times,
        Vogue, Wall Street Journal, GQ, Forbes and Fast Co.""")
    Outdoor_Voices.save()
    WSJ = Company(name="The Wall Street Journal", city="New York", state="NY",
        about= """ The Wall Street Journal is a global news organization
        that provides leading news, information, commentary and analysis.
        It is America's largest newspaper by total average circulation with
        more than 2.3 million digital and print subscribers and 36 million
        global digital visitors per month. Building on its heritage as
        the preeminent source of global business and financial news,
        the Journal includes coverage of U.S. & world news, politics,
        arts, culture, lifestyle, sports, and health.
        It holds 36 Pulitzer Prizes for outstanding journalism.
        The Wall Street Journal is published by Dow Jones,
        a division of News Corp. The Wall Street Journal iOS app
        has millions of users, and has been repeatedly featured by Apple.""")
    WSJ.save()
    Wayfair = Company(name="Wayfair", city="Boston", state="MA",
        about="""Over the past several years, Wayfair has been heavily 
        investing to build the best e-commerce shopping app across devices 
        to help consumers create a home they love, wherever they may be. 
        These efforts have resulted in a highly-rated 
        (4.8 stars on the App Store, 4.5 stars on Google Play),
         awarded (won the 2018 Webby for shopping), and featured 
         (Apple App of the Day) experience. But our job is far from finished, 
         with substantial opportunities to deliver against a bold app vision, 
         grow user adoption, improve innovative features like View in Room 3D 
         and Search with Photo, and invent the next wave of revolutionary 
         experiences.""")
    Wayfair.save()



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190224_2327'),
    ]

    operations = [
        migrations.RunPython(create_companies),
    ]
