# Generated by Django 2.1.7 on 2019-02-24 23:38

from django.db import migrations


def create_jobs(apps, schema_editor):
    Company = apps.get_model('jobs', 'Company')
    Job = apps.get_model('jobs', 'Job')

    Outdoor_Voices = Job(title="Front End Engineer", company=Company.objects.get(name="Outdoor_Voices"), 
        description=""" We are looking for a Front End Engineer to join our 
        technology team and make our digital experiences best-in-class as we 
        build out the next great activewear brand together. 
        The right candidate is a versatile engineer, able to jump 
        into a team environment, and make an immediate impact while 
        also being able to autonomously lead initiatives and drive them to completion. 
        S/he has the ability to work across desktop and mobile, and have the attention 
        to detail to create incredible digital user experiences.""", 
        link="https://jobs.lever.co/outdoorvoices/6d5de52a-3901-4eba-b987-6d1eefa331b2/apply?lever-source=themuse")
    Outdoor_Voices.save()

    Wall_Street = Job(title="iOS Software Engineer", company=Company.objects.get(name="The Wall Street Journal"),
        description="""We are looking for a iOS engineer to help us build and improve 
        the Wall Street Journal app for iPhone and iPad. As a mobile engineer, 
        you'll join our team of developers working together to bring innovative news 
        and storytelling techniques to our mobile platform. Our team consists of iOS, 
        Android, and backend developers working closely with product, design, and the newsroom.)""",
        link="https://wallstjobs.com")
    Wall_Street.save()
    
    Wayfair = Job(title="Product Manager, Mobie Apps", company=Company.objects.get(name="Wayfair"),
        description="""We are looking for an experienced Product Manager to help us take the 
        App to the next level of great. Your role will be to ensure that the App 
        provides the most loyal Wayfair customers with the most delightful and 
        immersive experience possible on their devices and unlocks a platform to 
        acquire the next generation of Wayfair users. This role will join a growing 
        App team that owns the product experience across all of Wayfair’s brands in 
        all of our targeted geographies (US, Canada, UK, Germany). This role will be 
        instrumental in growing a platform that already delivers more than $1B in annual 
        run rate revenue.)""", link="http://app.jobvite.com/CompanyJobs/Job.aspx?c=qI69VfwC&j=oPv28fwe&s=TheMuse")

    Wayfair.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190224_2327'),
    ]

    operations = [
        migrations.RunPython(create_jobs),
    ]
