# Generated by Django 2.1.7 on 2019-02-25 00:26

from django.db import migrations


def create_reqs_comp_exp(apps, schema_editor):

    Job = apps.get_model('jobs', 'Job')
    Company = apps.get_model('jobs', 'Company')
    Requirement = apps.get_model('jobs', 'Requirement')
    Experience = apps.get_model('jobs', 'Experience')
    Compensation = apps.get_model('jobs', 'Compensation')

    Outdoor_Voices_Req1 = Requirement(job=Job.objects.get(company=Company.objects.get(name="Outdoor_Voices")), description="Ship beautiful and functional products")
    Outdoor_Voices_Req1.save()
    Outdoor_Voices_Req2 = Requirement(job=Job.objects.get(company=Company.objects.get(name="Outdoor_Voices")), description="Improve code quality and best practices")
    Outdoor_Voices_Req2.save()

    Outdoor_Voices_Experience1 = Experience(job=Job.objects.get(company=Company.objects.get(name="Outdoor_Voices")), description="CS Degree")
    Outdoor_Voices_Experience1.save()
    Outdoor_Voices_Experience2 = Experience(job=Job.objects.get(company=Company.objects.get(name="Outdoor_Voices")), description="4+ years experience")
    Outdoor_Voices_Experience2.save()

    Outdoor_Comp = Compensation(job=Job.objects.get(company=Company.objects.get(name="Outdoor_Voices")), description="110K")
    Outdoor_Comp.save()

    WSJ_Req1 = Requirement(job=Job.objects.get(company=Company.objects.get(name="The Wall Street Journal")), description="One year iOS")
    WSJ_Req1.save()
    WSJ_Req2 = Requirement(job=Job.objects.get(company=Company.objects.get(name="The Wall Street Journal")), description="Bachelor Comp Sci")
    WSJ_Req2.save()

    WSJ_Experience1 = Experience(job=Job.objects.get(company=Company.objects.get(name="The Wall Street Journal")), description="Experiencing accessing API")
    WSJ_Experience1.save()
    WSJ_Experience2 = Experience(job=Job.objects.get(company=Company.objects.get(name="The Wall Street Journal")), description="Bash, Ruby, Javascript")
    WSJ_Experience2.save()

    WSJ_Comp = Compensation(job=Job.objects.get(company=Company.objects.get(name="The Wall Street Journal")), description="120-130")
    WSJ_Comp.save()

    Wayfair_Req1 = Requirement(job=Job.objects.get(company=Company.objects.get(name="Wayfair")), description="Lead project planning and update stakeholders")
    Wayfair_Req1.save()
    Wayfair_Req2 = Requirement(job=Job.objects.get(company=Company.objects.get(name="Wayfair")), description="Help translate department initiatives into manageable, actionable components")
    Wayfair_Req2.save()

    Wayfair_Experience1 = Experience(job=Job.objects.get(company=Company.objects.get(name="Wayfair")), description="3+ years experience in e-commerce or B2C product management")
    Wayfair_Experience1.save()
    Wayfair_Experience2 = Experience(job=Job.objects.get(company=Company.objects.get(name="Wayfair")), description="Track record of building high-impact consumer products")
    Wayfair_Experience2.save()

    Wayfair_Comp = Compensation(job=Job.objects.get(company=Company.objects.get(name="Wayfair")), description="115K")
    Wayfair_Comp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190224_2338'),
    ]

    operations = [
        migrations.RunPython(create_reqs_comp_exp),
    ]
